PROMPTS_EN = [
    "What made you smile today?",
    "What was the most special moment of the day?",
    "How did you feel when you woke up this morning?",
    "What was the most pleasant thing you heard today?",
    "What did you learn about yourself today?",
    "Who did you connect with today that made you feel good?",
    "What difficulty did you manage to overcome?",
    "What was the calmest moment of your day?",
    "If you had to choose a title for your day, what would it be?",
    "What would you like to remember from this day?",
    "What was the first thing you did this morning?",
    "What small decision made you feel good today?",
    "Was there anything that surprised you today?",
    "What was the most powerful thought you had today?",
    "At what point today did you feel proud of yourself?",
    "What was the simplest but most meaningful thing you did today?",
    "Who inspired you today and why?",
    "If you gave yourself advice for tomorrow, what would it be?",
    "What emotion dominated your day?",
    "If you could repeat one part of today, what would it be?",
    "What did you enjoy the most today?",
    "What’s one thing you would change about today?",
    "Which moments gave you energy today?",
    "What was the most meaningful thing you did for yourself today?",
    "How did you deal with a difficulty today?",
    "What was your last thought before you fell asleep yesterday?",
    "At what moment of the day did you feel gratitude?",
    "What smell, sound, or image calmed you today?",
    "What habit would you like to continue after today?",
    "What annoyed you today and why?",
    "Was there something you ignored but now wish you had noticed?",
    "What’s one thing you learned from someone else today?",
    "What’s the most important thing you want to do tomorrow?",
    "What word best describes your day?",
    "What was the most unexpected event of the day?",
    "Was there something that changed your mood?",
    "What was the most beautiful thing you saw today?",
    "What’s the first thing you'll do tomorrow and why?",
    "What was the most important 'no' you said today?",
    "What small step did you take today toward a bigger goal?",
    "Which part of the day would you like to keep forever?",
    "What helped you relax today?",
    "Who gave you courage today?",
    "What made you laugh?",
    "How did you positively impact someone else’s day?",
    "What habit do you want to stop and why?",
    "What was the most beautiful sunset or light you saw?",
    "What part of yourself did you recognize today?",
    "If you gave yourself a gift today, what would it be?",
]
