# Generated by Django 5.2 on 2025-05-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='highlights',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='diary_images/'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='mood',
            field=models.CharField(blank=True, choices=[('happy', '😊 Χαρούμενος'), ('sad', '😢 Λυπημένος'), ('stressed', '😰 Αγχωμένος'), ('calm', '😌 Ήρεμος'), ('angry', '😠 Θυμωμένος')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='tag',
            field=models.CharField(blank=True, choices=[('work', 'Εργασία'), ('health', 'Υγεία'), ('relationships', 'Σχέσεις'), ('personal', 'Προσωπικά'), ('other', 'Άλλο')], max_length=20, null=True),
        ),
    ]
