# Generated by Django 5.2 on 2025-05-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_journalanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
