# Generated by Django 5.2 on 2025-05-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='image_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
