# Generated by Django 5.2 on 2025-05-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_diaryentry_image_base64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='image_base64',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
