# Generated by Django 5.2 on 2025-05-08 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_alter_diaryentry_image_base64'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaryentry',
            name='image_base64',
        ),
    ]
