# Generated by Django 5.2 on 2025-05-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0009_remove_diaryentry_image_base64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
