# Generated by Django 5.2 on 2025-05-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0011_profileimage_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_subscribed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
